version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: eventhub-mysql
    environment:
      MYSQL_DATABASE: EventHub
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: eventhub-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/EventHub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - "8087:8087"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"

volumes:
  mysql_data:
